export enum NotificationType {
  // Meeting related
  MEETING_INVITATION = 'MEETING_INVITATION',
  MEETING_REMINDER = 'MEETING_REMINDER',
  MEETING_CANCELLED = 'MEETING_CANCELLED',
  MEETING_UPDATED = 'MEETING_UPDATED',

  // HR related
  LEAVE_REDUCTION_REQUEST = 'LEAVE_REDUCTION_REQUEST',
  LEAVE_REDUCTION_APPROVED = 'LEAVE_REDUCTION_APPROVED',
  LEAVE_REDUCTION_REJECTED = 'LEAVE_REDUCTION_REJECTED',
  COMPLAINT_CONFIRMATION = 'COMPLAINT_CONFIRMATION',
  HR_ANNOUNCEMENT = 'HR_ANNOUNCEMENT',

  // Attendance related
  LATE_ARRIVAL = 'LATE_ARRIVAL',
  ATTENDANCE_WARNING = 'ATTENDANCE_WARNING',
  ATTENDANCE_REMINDER = 'ATTENDANCE_REMINDER',

  // Financial related
  DUE_DATE_REMINDER = 'DUE_DATE_REMINDER',
  LIABILITY_REMINDER = 'LIABILITY_REMINDER',
  PAYMENT_DUE = 'PAYMENT_DUE',

  // Project related
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  PROJECT_DEADLINE = 'PROJECT_DEADLINE',
  PROJECT_ASSIGNMENT = 'PROJECT_ASSIGNMENT',

  // General
  GENERAL_ANNOUNCEMENT = 'GENERAL_ANNOUNCEMENT',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  WELCOME_MESSAGE = 'WELCOME_MESSAGE',
}
